TAMULib/SAGE

src/main/resources/templates/index.html

The index changes in the referenced commit was not intended to be committed.
see: https://github.com/TAMULib/Sage/pull/13/commits/dd48d0d31e3db031476b64581e2f5a0409177c97#diff-7bce6bf37aaa3e41c61d593299d13979

Revert unintended changes to index.html

---

.travis.yml

The coverage report is not being correctly combined and coveralls would only pick one or the other as the number.
By utilizing parallel builds, coveralls knows that the test results should be combined.
Webhooks and a few environmental variables are required to achieve this.
Maven happens to directly support assignment of the build settings.
Karma needs the environmental variables assigned.
see: https://docs.coveralls.io/parallel-build-webhook
see: https://travis-ci.community/t/how-can-i-share-coverage-information-between-build-stages-in-prs-from-forks/859/12

Help Travis-CI tell Coveralls to combine all tests via parallel builds

---

src/main/java/edu/tamu/sage/model/Source.java
src/main/java/edu/tamu/sage/model/Writer.java
src/main/webapp/app/repo/sourceRepo.js
src/main/webapp/app/repo/writerRepo.js

Use `@NotNull` to utilize the validation on NULL values received.
Use `nullable = false` on the `@Column` to setup the database with `NOT NULL` column property.
Assign defaults to the scaffold to ensure NULL is never sent by the frontend.

[D-01276] Restrict NULL values from being used, for Sources and Writers

---

package.json
src/main/java/edu/tamu/sage/controller/handler/SourceControllerAdvice.java
src/main/java/edu/tamu/sage/exceptions/SourceFieldsException.java
src/main/java/edu/tamu/sage/exceptions/SourceNotFoundException.java
src/main/java/edu/tamu/sage/exceptions/SourceServiceException.java
src/main/java/edu/tamu/sage/service/SolrDiscoveryService.java
src/main/java/edu/tamu/sage/service/SolrSourceService.java
src/main/java/edu/tamu/sage/service/SourceService.java
src/main/webapp/app/views/modals/createDiscoveryViewModal.html
src/main/webapp/app/views/modals/createInternalMetadatumModal.html
src/main/webapp/app/views/modals/createJobModal.html
src/main/webapp/app/views/modals/createOperatorModal.html
src/main/webapp/app/views/modals/createReaderModal.html
src/main/webapp/app/views/modals/createSourceModal.html
src/main/webapp/app/views/modals/createWriterModal.html
src/main/webapp/app/views/modals/updateDiscoveryViewModal.html
src/main/webapp/app/views/modals/updateInternalMetadatumModal.html
src/main/webapp/app/views/modals/updateJobModal.html
src/main/webapp/app/views/modals/updateJobScheduleModal.html
src/main/webapp/app/views/modals/updateOperatorModal.html
src/main/webapp/app/views/modals/updateReaderModal.html
src/main/webapp/app/views/modals/updateWriterModal.html

Implement generic `SourceServiceException`.
Implement specific Exceptions: `SourceFieldsException` and `SourceNotFoundException`.
Give the user explicit feedback when unable to connect to the service and use a **HTTP 503**.
For all other source errors, use `SourceServiceException` with the less explicit **HTTP 500**.
The URI is provided as a simple way to provide which source failed.
(It may or may not be more desirable to use the source name and not the URI.)
Make sure the appropriate modals exclusively receive the core exceptions.
Set timeout of errors to 30 seconds.
depends: TAMULib/Weaver-UI-Core#145.

[B-03915] Handle exception when source cannot be reached and provide feedback to frontend

---

src/main/resources/import.sql

Do not manually insert the ID column because that is a SERIAL/AUTO-INCREMENT column.
Manually adding it prevents the auto-increment column from working.
Specifically, the auto-incremented column ends up still having a value of 1 after the initial import and further attempts in the UI to add any metadata will fail due to id conflicts.
Do not check to see if columns are already imported.
The property `spring.datasource.data: classpath:/import.sql` should be disabled after the initial import to prevent further inserts.
(It is a shame that `spring.jpa.hibernate.ddl-auto` doesn't also respect/handle `spring.datasource.data`.)

[D-01282] Use simpler import.sql, fixing ability to insert Internal Metadata Management

---

src/main/webapp/app/views/modals/createDiscoveryViewModal.html
src/main/webapp/app/views/modals/updateDiscoveryViewModal.html
src/main/webapp/tests/unit/controllers/management/discoveryViewManagementControllerTest.js

`property="idInfoText"` is Not valid and the valid `property="infoText"` is already defined.
Also, ids such as "createName" and "updateName" could be used on other modals very easily.
Use the full model name in the id to further guarantee distinctness.

[D-01289] Info Text in Discovery View does not save on Create

---

src/main/java/edu/tamu/sage/model/Sourcable.java
src/main/java/edu/tamu/sage/model/Source.java
src/main/java/edu/tamu/sage/model/validation/DiscoveryViewValidator.java
src/main/java/edu/tamu/sage/service/SolrDiscoveryService.java
src/main/webapp/app/controllers/management/discoveryViewManagementController.js
src/main/webapp/app/controllers/management/sourceManagementController.js
src/main/webapp/app/model/sourceModel.js
src/main/webapp/app/repo/discoveryViewRepo.js
src/main/webapp/app/repo/sourceRepo.js
src/main/webapp/app/views/modals/createSourceModal.html
src/main/webapp/app/views/modals/updateSourceModal.html
src/main/webapp/tests/mocks/model/mockSource.js
src/main/webapp/tests/mocks/repo/mockDiscoveryViewRepo.js
src/main/webapp/tests/mocks/repo/mockSourceRepo.js

When the boolean "requiresFilter" is TRUE, and the "filter" property on a Discovery View is empty, then use "*.*" for Discovery View.
Where Filter is not allowed to be "*.*", the "requiresFilter" can be set to FALSE.
This fixes structural an accessibility issues with the `sourceToCreate.readOnly` field tag (radio group label must be associated with either ARIA or a <fieldset> and <fieldset> is a badly designed HTML tag). The `sourceToCreate.readOnly` field tag must be grouped with the appropriate class `form-group` for proper display an positioning for subsequent fields.

[B-03977] Boolean to toggle "filter" as being required on a per-core basis

---

src/main/java/edu/tamu/sage/model/DiscoveryView.java
src/main/java/edu/tamu/sage/model/FacetField.java
src/main/java/edu/tamu/sage/model/response/FacetFilter.java
src/main/resources/templates/index.html
src/main/webapp/app/config/apiMapping.js
src/main/webapp/app/controllers/management/discoveryViewManagementController.js
src/main/webapp/app/model/facetFieldModel.js
src/main/webapp/app/model/metadataFieldModel.js
src/main/webapp/app/repo/discoveryViewRepo.js
src/main/webapp/app/views/modals/confirmDeleteDiscoveryViewModal.html
src/main/webapp/app/views/modals/createDiscoveryViewModal.html
src/main/webapp/app/views/modals/updateDiscoveryViewModal.html
src/main/webapp/tests/mocks/model/mockFacetField.js
src/main/webapp/tests/mocks/model/mockMetadataField.js
src/main/webapp/tests/mocks/repo/mockDiscoveryViewRepo.js
src/main/webapp/tests/unit/controllers/management/discoveryViewManagementControllerTest.js
src/main/webapp/tests/unit/models/facetFieldModelTest.js
src/main/webapp/tests/unit/models/metadataFieldModelTest.js

Maintain binding for active tab, clone model for modal scope.
Redesign how the first row for FacetFields, SearchFields, and ResultMetadataFields are used by implementing ng-ifs and providing defaults.
Correctly calculate tabs length and make sure the active tab is always valid.
The `$scope.active` was renamed to `$scope.tabs.active` so that the length of tabs could be grouped with the active tab and make calculations consistent.
The number of tabs is 4 and not 3, so set length to 4.
Creating a DiscoveryView now directly handles initializing a default source, if possible, and subsequently loading of the fields.
Implement MetadataField and FacetField models in the UI.
Don't add the default searchField in the scaffold.
Instead, append the default after the scaffold is used so that a new …

[D-01284] Discovery View fields (metadatafields) do not always show when there is a valid value

---

src/main/webapp/app/controllers/management/discoveryViewManagementController.js
src/main/webapp/tests/unit/controllers/management/discoveryViewManagementControllerTest.js

The select lists options associated with the fields should not be empty.
Failing to delete the DiscoveryView after closing the model caused subsequent edits to not populate the select lists.
Facet Fields and Result Metadata Fields should be allowed to be not specified (when no key/option is selected for a given field).

[D-01284] discovery view fields empty issues

---

package.json
src/main/webapp/app/views/modals/confirmDeleteDiscoveryViewModal.html
src/main/webapp/app/views/modals/createDiscoveryViewModal.html
src/main/webapp/app/views/modals/updateDiscoveryViewModal.html

Upgrade to Weaver-UI-2.0.5, which includes relevant fixes/improvements in the error handling.
Catch `discovery-view` channel in Discovery View modals.

[D-01285] discovery view error handling

---

src/main/java/edu/tamu/sage/controller/SourceController.java
src/main/webapp/app/config/apiMapping.js
src/main/webapp/app/controllers/management/discoveryViewManagementController.js
src/main/webapp/app/model/sourceModel.js
src/main/webapp/app/views/modals/createDiscoveryViewModal.html
src/main/webapp/app/views/modals/updateDiscoveryViewModal.html
src/main/webapp/tests/mocks/model/mockSource.js
src/main/webapp/tests/unit/controllers/management/discoveryViewManagementControllerTest.js
src/main/webapp/tests/unit/models/sourceModelTest.js

Adds and implements `/source/solr/test/ping` endpoint.
There are also some existing endpoints, but these are currently outdated and do more than is necessary.
Furthermore, the other endpoints produce errors and the "test/ping" endpoint is intended to produce warnings.
The ping (and only a ping) is performed when selecting any given `source` on the first tab in the Discovery View management's first tab.
If the ping fails, a warning is presented to the user.
If the user continues to the next tab despite the warning, an error will be presented as usual when trying to fetch the fields.
The errors should also be presented when the `filter` changes and not just the `source`.

[B-03916] As a curator, I would like a warning about unavailable sources/destinations (collections/cores) when adding them to new objects

---

src/main/webapp/app/views/directives/breadcrumbs.html

I had previously designed the breadcrumb to not be a link.
When I managed to get the link to work (using the "reload" design), I forgot to update the link when home.active is TRUE.

Home breadcrumb should always be a link

---

.travis.yml

After "Sage" was renamed to "SAGE", coveralls stopped working.
The Java tests were using "SAGE" and the angularjs tests were using "Sage".
This resulted in the parallel build never completing.
Use "repo" property to manually enforce all uppercase "SAGE".
see: https://docs.travis-ci.com/user/deployment/pages/#further-configuration

Test coverage integration

---

src/main/java/edu/tamu/sage/controller/DiscoveryViewController.java
src/main/java/edu/tamu/sage/service/SolrDiscoveryService.java
src/main/webapp/app/model/discoveryContextModel.js
src/main/webapp/app/views/discovery/discovery-context.html

Resolves #145 by:
- Using encodeURIComponent on the filter value parameters before sending them to the server to prevent Tomcat level bad requests
- Using Apache ClientUtils to escape the search and facet values before querying solr
- Introducing a 'fv::' prefix on filter values to enable server side parsing of multiple facet queries against the same facet key. This approach is used because Tomcat only accepts query parameter arrays in the form 'field=value1,value2,value3' and Spring's built in RequestMap serialization doesn't know how to parse a List/Set when nested within a Map.

[145] Multiple fixes for solr query and facet search

---

src/main/java/edu/tamu/sage/service/SolrDiscoveryService.java

This is a followup PR for PR #162
The current behavior of SAGE before 162 was to accept solr special characters when searching. 
This followup PR restores that behavior.

[FOLLOWUP][145] Remove character escaping for solr search, leave in place for facet

---

src/main/webapp/app/controllers/appLoginController.js
src/main/webapp/app/views/modals/loginModal.html

AppLoginController.js needs to extend  weaver LoginController, not AuthenticationController or the email login functionality is broken due to the different login method implementations.
https://github.com/TAMULib/Weaver-UI-Core/blob/2.x/app/controllers/authenticationController.js#L54
https://github.com/TAMULib/Weaver-UI-Core/blob/2.x/app/controllers/loginController.js#L7

Restore email registration login functionality

---

solr/config/managed-schema
src/main/java/edu/tamu/sage/service/SimpleProcessorService.java

Resolves #187 by passing through solr doc values that have more than one entry and using the first entry when there is only one value. The UI is already capable of displaying multiValued entries.
Using the first/only entry for single values preserves backwards compatibility with existing operators that assume a single string rather than an ArrayList. We will likely need to modify the operator pipeline to support both multivalued and single string entries at some point.
This PR also removes some dead legacy code from the early days of the aggregation process. 
This PR also updates the docker solr schema by:
- converting 'filename' into a multiValued field
- adding a multiValued dynamic field '*_txt_en_split_mv' to support optional tokenized indexing of multiValued fields
- converting …

[187] Updates to SimpleProcessor to handle multivalued fields

---

src/main/webapp/app/resources/styles/sass/directives/single-result.scss

Resolves #208 by using css to hide the title altogether because...
The labels in many of our manifests have multiple entries..
Mirador 2.7.x is hard-coded deep in its bowels to add line breaks between multi-valued entries:
https://github.com/ProjectMirador/mirador/blob/v2.7.0/js/src/utils/jsonLd.js#L61
Line breaks are special in CSS. Pseudo classes don't work on them, and the only cross browser option to neutralize them is with display:none. This hides the break, but without pseudo classes, there's no way to add a space between the entries.
There's also no way to turn the title off in 2.7.x.
In currently unreleased 3.x, the [title can be turned off](https://github.com/ProjectMirador/mirador/pull/2630), and 
it looks like [multi-valued entries are handled better …

[208] hide title in Mirador viewer

---

src/main/webapp/app/controllers/discoveryContextController.js
src/main/webapp/app/resources/styles/sass/discovery-context/_all.scss
src/main/webapp/app/views/discovery/discovery-context.html

Resolves #204 
Resolves #205 
The (un-break-able) angular forEach is used because there is some sort of pre-existing race/bind condition that prevents pure javascript loops from working when re-initializing the currentSearchField. They set the scoped value properly, but then angular comes along and wipes it out.

[204][205] Restore search select and move search button to right side

---

src/main/webapp/app/directives/presentValueDirective.js

The more complex url detection regex is leading to too much recursion errors when applied to the id field in full view.
This simpler pattern only checks for the protocol at the start of the string. This matches the card description and doesn't trigger the recursion error.

[222][FOLLOWUP] Use simpler regex pattern for urls to avoid full view recursion error

---

src/main/webapp/app/controllers/management/discoveryViewManagementController.js
src/main/webapp/app/views/modals/updateDiscoveryViewModal.html

Resolves #186 
Enhances validation for search and facet fields to prevent users from advancing a Discovery View create or update until they fully populate the necessary fields for that widget.
This PR meets the requirements of 186 but is a workaround for an underlying issue that is causing the blank selections in the first place:
https://github.com/TAMULib/SAGE/issues/280
If 280 can be fixed, users won't have a blank option at all.

[186] Require facet and search fields to be populated in UI

---

src/main/webapp/app/resources/styles/sass/discovery-context/_all.scss
src/main/webapp/app/views/discovery/discovery-context.html

Resolves #266 by adding appropriate presentations for different scenarios:
- When there is a logo and title, the full presentation is shown
- When there is a logo but no title, the logo appears by itself, with no gray box overlay (the description will be ignored, if present).
- When there is no logo but a title, the small gray box from the full presentation is shown, including the description, if available.
- Nothing will display when there is no logo and no title (the description will be ignored, if present).
This PR also corrects the situation where a short title leads to a gray box that fails to cover the full width of the parent logo container.

[266] Presentation for collections with description/info but no logo

---

src/main/webapp/app/model/discoveryContextModel.js

Since [278](https://github.com/TAMULib/SAGE/pull/278) made it possible for there to be multiple facets with the same facet key, we need to make the UI sorting mechanism added in [275](https://github.com/TAMULib/SAGE/pull/275/files) unique by facet key and value.

[FOLLOWUP][211][212] Make sorted filter keys unique by filter key and value

---

src/main/java/edu/tamu/sage/model/Base64EncodeOp.java
src/main/java/edu/tamu/sage/model/ConstantOp.java
src/main/java/edu/tamu/sage/model/DateNormalizationOp.java
src/main/java/edu/tamu/sage/model/DefaultOp.java
src/main/java/edu/tamu/sage/model/RegexReplaceOp.java

The value reference to the collection entry within the forEach doesn't want to share its scope, so replace the whole collection instead.
Edit: It looks like this is due to the string manipulation on an object, not the iteration.

[FOLLOWUP][201] Replace entire Collection when manipulation Collections in Operators

---

src/main/webapp/app/resources/styles/sass/directives/single-result.scss
src/main/webapp/app/resources/styles/sass/discovery-context/_all.scss

No longer truncating metadata labels

---

pom.xml
src/main/java/edu/tamu/sage/service/SimpleProcessorService.java

```
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at https://api-dev.library.tamu.edu/solr/sage-core: ERROR: [doc=aHR0cHM6Ly9hcGktZGV2LmxpYnJhcnkudGFtdS5lZHUvZmNyZXBvL3Jlc3QvYS10aW1lLW9mLXJlc29sdmUtMjAyMC0wNC0zMF9vYmplY3RzLzEwMw==] unknown field ''
at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:577)
at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:106)
at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:71)
at …
```

prevent empty string field mapping on solr document

---

.gitignore
Gruntfile.js
package.json
src/main/resources/templates/index.html
src/main/webapp/app/directives/contentViewerDirective.js
src/main/webapp/build-js/TAMUMirador.src.js

This PR resolves #399 by manually building Mirador 3 with grunt-webpack to enable packaging the image tools plugin and potentially other future plugins.
This required the implementation of a wrapper object to provide access to Mirador's state while in the context of the angularjs app.
The destroy method in particular is needed to properly unmount the Mirador instance when the contentViewer directive is unloaded by angularjs. This is necessary to prevent rendering issues if a user navigates to another Mirador based discovery view.
This solution appears to be working without issue, but I couldn't find any documented examples of dynamically generating and destroying Mirador instances. The 'proper' use of Mirador 3 seems to be loading one instance and then using redux actions to update it as …

[399] Fix build by integrating with Mirador 3 + Image Tools Plugin

---

Gruntfile.js
package.json
src/main/resources/templates/index.html
src/main/webapp/app/directives/contentViewerDirective.js

Resolves #399 
I've adjusted the Mirador 3 settings to bring us closer to the existing Mirador 2 presentation.
The main difference is that Mirador 2 provided a GUI for image manipulation (rotation, saturation, brightness, etc) that passed through to its OpenSeaDragon embed that was visible by default. Mirador 3 doesn't seem to provide that GUI at all, and plugins would be required to recreate that functionality.

[399] Fix npm build by upgrading to Mirador 3

---

src/main/resources/templates/index.html
src/main/webapp/app/resources/styles/sass/app.scss

This PR addresses the following two issues:
1) inconsistent sizing from bootstrap classes between SAGE and the Library main site. This is due to Bootstraps use of the rem unit, and SAGE's lack of font-size definition at the HTML element level.
2) The absence of the Lato font.
Fixes # (issue)

Added rem rule to html and lato font

---

src/main/java/edu/tamu/sage/controller/DiscoveryViewController.java
src/main/java/edu/tamu/sage/controller/IternalMetadataController.java
src/main/java/edu/tamu/sage/controller/JobController.java
src/main/java/edu/tamu/sage/controller/OperatorController.java
src/main/java/edu/tamu/sage/controller/ReaderController.java
src/main/java/edu/tamu/sage/controller/SourceController.java
src/main/java/edu/tamu/sage/controller/UserController.java
src/main/java/edu/tamu/sage/controller/WriterController.java

Each of the controllers were implementing their delete functionality using `deleteById`. This method does not result in a broadcast to the front end. By replacing each of those method calls with the `delete` method, the broadcast occurs and the lists in the UI are update on delete.
Fixes #457 

Using the delete method, not deleteById, for ws broadcast

---

.gitignore
src/main/resources/application.yml
src/main/resources/data.sql

Works with h2 memory and file, postgres locally and in docker.
```
version: '3.7'
networks:
weaver:
services:
db:
image: postgres:10.22-alpine
environment:
POSTGRES_USER: sage
POSTGRES_PASSWORD: sage
POSTGRES_DB: sage
ports:
- 5432:5432
networks:
- weaver
service:
container_name: sage
hostname: sage
build:
dockerfile: Dockerfile
context: './'
args:
- NPM_REGISTRY=${NPM_REGISTRY}
- NODE_ENV=${NODE_ENV}
image: ${IMAGE_HOST}/${SERVICE_PROJECT}${SERVICE_PATH}:${IMAGE_VERSION}
ports:
- 9000:9000
env_file:
- .env
networks:
- weaver
depends_on:
- db
```

Alter sequence if exists

---

src/main/webapp/app/controllers/management/discoveryViewManagementController.js
src/main/webapp/app/controllers/management/readerManagementController.js
src/main/webapp/app/controllers/management/writerManagementController.js

The problem is that the id is removed from the form before submitting. This is done to trigger the generation of a new ID automatically on the backend. If the validation fails, the form no longer has the ID.
Fix this by saving the ID and restoring the ID to the form if clone submit did not succeed.
This same exact problematic logic is in the `ReaderManagementController` and the `WriterManagementController`. Given the identical scope, the same fix is applied to each of those as well.
Fixes #401

Issue 401: Cloning modals unresponsive after validation error.

---

package.json

Fix child dependencies that are coming in with insecure versions. This is based on the `npm list --depth=100` and considers what is reported by dependabot for Sage.
see: https://github.com/TAMULib/SAGE/security/dependabot/37
see: https://github.com/TAMULib/SAGE/security/dependabot/34
Fixes #468

Issue 468: Security fixes for: minimatch and qs.

---

src/main/webapp/app/controllers/discoveryContextController.js

There are several areas where the is undefined logic can be improved. Fixing these does not solve the problem and such changes have been omitted.
The problem is that the form has an initial value that is undefined. When the form gets submitted, via a search button click or a sort button click, then the undefined gets translated into the string 'undefined'.
The immediate solution is to always initialize the value as an empty string before processing any of the URL arguments on first load.
Fixes #476

Issue 476: Sort order toggle button appends value=undefined to URL, breaking the search.

---

src/main/java/edu/tamu/sage/controller/IternalMetadataController.java
src/main/java/edu/tamu/sage/controller/OperatorController.java
src/main/java/edu/tamu/sage/model/repo/InternalMetadataRepo.java
src/main/webapp/app/views/modals/cloneReaderModal.html
src/main/webapp/app/views/modals/createReaderModal.html
src/main/webapp/app/views/modals/updateReaderModal.html

There are additional management fields that are not alphabetically sorted that were missed in the previous PR (#486).
There are two cases where I opted to perform the sorting on the back-end.
The metadaum and operators.
On the UI side, both of these are either `validatedinput` or `multi-suggestion-input` fields.
I do not see any obvious support in weaver-ui-core that supports the sorting on the list.
Therefore, I opted to sort on the back-end.
I used the DB order for InternalMetadata.
I used the Java array string sort for the Operator given the current design.
The type aheads on the Readers have the UI orderBy filter added.
The Reader Field Mappings could also have additional sorting, but this requires more discussion and is omitted.
Fixes #475
Please describe the tests that you ran to …

Issue 475: Alphabetic follow up, addressing more management fields.

---

solr/Dockerfile

Adding additional cores for development and testing should be easier. The goal here is to make this easier by utilizing docker arguments.
The solr user is also abstracted into an argument for possible arg-based changes, if ever.
The default core is abstracted into `MAIN_CORE` docker build argument, with a default of `sage-discovery`. The additional cores are abstracted into `EXTRA_CORES` docker build argument. This is done primarily because docker has very poor (non-existent) loop and conditional handling. The `COPY` command needs to be performed in a loop or in conditions but such support is unavailable.
This takes the approach of checking if `EXTRA_CORES` is empty and if not loop over space separated core names. The `MAIN_CORE` must be pre-created so that the configuration can be …

Enable support for multiple SOLR cores via Docker build arguments.

---

src/main/webapp/app/model/discoveryContextModel.js

This is the solution created while investigating the spike #492.
This addresses the problem by replacing the `#` (U+0023) character with `%23` for relevant situations (properties in the search).
This needs to be tested for regressions, specifically checking for data in facets and filters that have the `#` (U+0023) character.
Fixes #502

Issue 502: Angularjs $location.search is not safe to use when passing '#'.

---

src/main/webapp/app/controllers/management/internalMetadataManagementController.js
src/main/webapp/app/controllers/management/operatorManagementController.js
src/main/webapp/app/controllers/management/readerManagementController.js
src/main/webapp/app/controllers/management/sourceManagementController.js
src/main/webapp/app/controllers/management/writerManagementController.js
src/main/webapp/tests/unit/controllers/management/internalMetadataManagementControllerTest.js
src/main/webapp/tests/unit/controllers/management/jobManagementControllerTest.js
src/main/webapp/tests/unit/controllers/management/operatorManagementControllerTest.js
src/main/webapp/tests/unit/controllers/management/readerManagementControllerTest.js
src/main/webapp/tests/unit/controllers/management/sourceManagementControllerTest.js
src/main/webapp/tests/unit/controllers/management/writerManagementControllerTest.js

It uses the original values which is shared in the modal, which is not desirable. Upon clicking the `X` or the `Cancel` button, the original model value is updated, so utilized the copy() to resolve this behavior.
Fixes #480

Clear values upon closing is resolved using angular.copy().

---

src/main/resources/application.yml

Treat the referenced problem as a configuration problem.
Provide documentation in the `application.yml` to help avoid the situation.
Fixes #506

Issue 506: Document a possible solution to prevent metadata key enumeration problems.

---

src/main/webapp/app/components/facetWidgetComponent.js
src/main/webapp/app/filters/simpleAsciiFilter.js
src/main/webapp/app/views/components/facetWidget.html
src/main/webapp/tests/unit/filters/simpleAsciiFilterTest.js

Provide a simple character sanitizer that strips out all ascii and non-ascii characters that are not in the specified range or list of simple characters.
The added unit test includes one or more Unicode whitespace that may or may not be visibly printed. I generated these using my utf8 program, like this:
```
echo "h$(utf8 -cB U+200A)i$(utf8 -cB U+200D)j"
```
The code points can be verified using a program like my byte_dump program:
```
echo -en "a b  c\fd e f g h i‍j" | byte_dump -wUt 4
```
Fixes #497
To manually test this in the UI, perform all of the appropriate steps to …

Issue 497: Sanitize ID Field.

---

src/main/webapp/app/filters/boldMatchFilter.js
src/main/webapp/tests/unit/filters/boldMatchFilterTest.js

The bold match filter should not bold empty text but does.
The unit test has to comment out code and effectively be disabled due to this.
Fixes #519

Issue 519: Fix Bold Match Filter returning an empty bold markup.

---

src/main/java/edu/tamu/sage/service/SolrDiscoveryService.java

This ensures matches of 0 never appear in the facets. The SolrQuery class provides a handy `setFacetMinCount()` method to easily utilize this functionality.
Fixes #498

Issue 498: Always set facet min count to 1.

---

solr/config/managed-schema
solr/config/solrconfig.xml
solr/config/stopwords.txt
src/main/java/edu/tamu/sage/controller/DiscoveryViewController.java
src/main/java/edu/tamu/sage/service/SolrDiscoveryService.java

This commit represents the results of the investagtion described in issue #515.
There are several things to consider and this takes a compatible approach focusing on re-using as much of the existing design as possible. There is some inconvenience or cost for taking this approach.
The use of `df` (default field) is not implemented with these changes but is strongly recommended for future Sage releases. This does not update the documentation (such as the Github documentation). That documentation needs to be updated following this set of changes.
**Source Code Changes**
Change the default query from `*:*` to just `*`.
This restricts the searches to just the fields being searched rather than searching on everything. This can be further improved by providing a `df` (default field). When …

Issue 515: Redesign Solr search process, particularly the Solr Core.

---

src/main/java/edu/tamu/sage/service/SolrDiscoveryService.java

The behavior of manually adding the selected field as a string to the query causes problems. Instead, set the selected field as the Default Field 'df' in the query.
Fixes #514

Issue 514: Use Default Field 'df' to prevent syntax problems.

---

solr/config/managed-schema

The text_ws should use more of the properties off of the standardized string represented by the text_general field and text_en_split field.
The whole_string should not use the lower case filter.
This also automatically performs multilingual matching of sorts.
Searching for the English word "Reserved" for example may find German matches.
Attempts to use `solr.WordDelimiterGraphFilterFactory` (including with `preserveOriginal="1"`) have solved the immediate problem but introduced a regression where the quote strings never match anymore. This has graph has been removed from this change set.
Fixes #515

Issue 515: Improve text_ws and whole_string query searching.

---

src/main/java/edu/tamu/sage/service/SolrDiscoveryService.java

One would expect that when the default field is set to say `origin`, then the default wild card would be against the `origin`. This is not the case.
If there is no value but there is a search field, then prepend the search field before the wild card like `origin:*`.
The regressed behavior would result in an parsed query of:
```json
{
"responseHeader":{
"status":0,
"QTime":0,
"params":{
"q":"*",
"df":"origin",
"debug":"query",
"sow":"true",
"rows":"0",
"_":"1675954886742"}},
"response":{"numFound":6494,"start":0,"docs":[]
},
"debug":{
"rawquerystring":"*",
"querystring":"*",
"parsedquery":"MatchAllDocsQuery(*:*)",
"parsedquery_toString":"*:*",
"QParser":"LuceneQParser"
}
}
```
Adding the default search of `origin` before the wild card results in:
```json
{
"responseHeader":{
"status":0, …
```

Default Field and wild cards don't work as expected.

---

src/main/webapp/app/components/multiSuggestionInputComponent.js
src/main/webapp/app/controllers/management/discoveryViewManagementController.js
src/main/webapp/app/filters/boldMatchFilter.js

The autocomplete drop down is requiring the input variable to be modified. The return value is not being processed at all.
When there is no matches, the input value must still be modified, even if the modification makes it empty.
While investigating this, a ton of white space ended up being auto-corrected. I decided to leave those corrections.

Regression in boldMatch filter causing autocomplete drop down to not work as expected.

---

src/main/webapp/app/resources/styles/sass/components/result-entry.scss

The commit 696e359c4709b8b1d3051b86f2b2900ee0ddc3bf introduced this regression. Text is not wrapping anymore.
As a quick fix, add a word break to the styling.

Fix regression in field spanning width with overly long text.

---

src/main/java/edu/tamu/sage/service/SolrSourceService.java

In practice, restricting the fields to only ones that have data makes the UI hard to use. Trying to configure a Discovery View is causing problems with being unable to select the data. Dynamic fields that are not stored may not show up when they should be available.
This change makes the field display more consistently and allows for all fields to be seen and selected from.

Do not restrict fields filter to fields that have data types populated.

---

solr/configsets/sage-1_0/conf/managed-schema.xml
solr/configsets/sage-1_0/conf/solrconfig.xml

Using the incorrect copyfield name results in a failure when populating the index.
The filter query does not work as expected for "whole" strings.
Change these "whole" strings used in core types to "string" (this will need further runtime testing).
The PR #549 introduced the "multivalue" field across the board.
Play it safe and do not add the explicit "multivalue" attribute to the core types.
The date type cannot be used for `date_published` and `date_created` because the provided dates may not be in a supported format.
Both `collection` and `resource` are multivalued in DSpace.
Change the solr core to support multiple values for both `collection` and `resource`.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any …

The sage-1_0 should use "*_string" rather than "*_str", "string" rather than "whole", and other core related changes.
